"""
Test script to show the EXACT prompt format that would be sent to Sora 2.

The actual prompts are generated by GPT-4-turbo in two stages, but this shows:
1. The exact code path where prompts are logged
2. The exact format/structure of the prompts
3. How to see the actual prompts in logs
"""

import sys
import os

# Add backend to path to import modules
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'backend'))

# User's original prompt
USER_PROMPT = """The Chronos Elite is a luxury smartwatch for busy professionals. It features a 7-day battery life and advanced health tracking, allowing users to stay connected and on top of their wellness goals without constant charging."""

print("=" * 80)
print("EXACT SORA 2 PROMPT FORMAT")
print("=" * 80)
print("\n1. USER INPUT PROMPT:")
print("-" * 80)
print(USER_PROMPT)
print()

print("2. PROMPT TRANSFORMATION FLOW:")
print("-" * 80)
print("""
Your prompt goes through this transformation:

Step 1: Stage 1 LLM (llm_enhancement.py)
  - Input: Your user prompt
  - Output: JSON blueprint with 4 scenes
  - Each scene has fragments: visual, action, camera, lighting, mood, product_usage

Step 2: Scene Assembler (scene_assembler.py)  
  - Input: Fragments from Step 1
  - Output: 1-2 sentence cinematic paragraph
  - This is the EXACT prompt sent to Sora 2

Step 3: Sora 2 API Call (video_generation.py)
  - The cinematic paragraph from Step 2 is sent as the "prompt" parameter
  - Additional parameters: duration=4, aspect_ratio="portrait", quality="high"
""")

print("3. WHERE TO SEE THE EXACT PROMPTS:")
print("-" * 80)
print("""
The exact prompts are logged in two places:

A) Scene Assembler Output (scene_assembler.py, line 61-62):
   - Logs: "[Scene Assembler Output]" followed by the paragraph
   - This is the prompt that will be sent to Sora 2

B) Sora 2 API Call (video_generation.py, lines 370-377):
   - Logs: "🎬 EXACT SORA-2 PROMPT FOR SCENE X"
   - Shows the exact prompt text being sent to Replicate API
   - Format:
     ================================================================================
     🎬 EXACT SORA-2 PROMPT FOR SCENE 1 (duration: 4s):
     ================================================================================
     PROMPT TEXT:
     [The exact prompt text here]
     ================================================================================
""")

print("4. EXACT PROMPT FORMAT (Based on System Prompts):")
print("-" * 80)
print("""
Based on the Scene Assembler system prompt rules, each Sora 2 prompt will be:

- 1-2 sentences maximum
- Purely visual/filmable description
- No product name (uses "the product" instead)
- No appearance adjectives (no color, shape, materials)
- Includes camera motion description
- Ends with ambient sound description
- No mood commentary or style phrases

Example format (what it would look like):
"A person checking their wrist in a professional office setting, 
the camera slowly gliding across the scene in soft daylight, 
with quiet office ambience."
""")

print("5. COMPLETE SORA 2 API PARAMETERS:")
print("-" * 80)
print("""
For each scene, the exact API call to Replicate would be:

{
  "prompt": "[1-2 sentence cinematic description from Scene Assembler]",
  "duration": 4,
  "aspect_ratio": "portrait",
  "quality": "high"
}

The "prompt" field contains the exact text generated by the Scene Assembler LLM.
""")

print("=" * 80)
print("TO SEE THE ACTUAL EXACT PROMPTS:")
print("=" * 80)
print("""
1. Run a video generation with your prompt via the API
2. Check the application logs (logs/app.log)
3. Look for:
   - "[Scene Assembler Output]" - shows the prompt before enrichment
   - "🎬 EXACT SORA-2 PROMPT FOR SCENE X" - shows the final prompt sent to Sora 2

The logs will show the EXACT prompts generated by GPT-4-turbo for your specific input.
""")

print("\n" + "=" * 80)
print("CODE REFERENCES:")
print("=" * 80)
print("""
- Scene Assembler: backend/app/services/pipeline/scene_assembler.py
- Prompt logging: backend/app/services/pipeline/video_generation.py:370-377
- LLM Enhancement: backend/app/services/pipeline/llm_enhancement.py:205-209
""")

